name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip
        run: python -m pip install -U pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Health check (parquet + DuckDB)
        run: python scripts/health_check.py
      - name: Install dev tools
        run: pip install ruff pytest
      - name: Lint
        run: ruff check .
      - name: Tests
        run: pytest -q
